### ISSUE TITLE
"Oops, an error occurred!" when choose a backendlayout

### ISSUE THREAD

**Issue by SchluribumbiVonDerZukunft** [benjaminkott/packagebuilder#10]
I Installed a new sitepackage in a new typo3 installation. When i choose a backendlayout, there is only the message "Oops, an error occurred!". In addition to this, the backendlayout "Default" has no name in the backend. Instead of the name i can click on a white placeholder for the name.

Because i installed the sitepackage in a new typo3 installation, and because i followed step by step the youtube video from benji an mathias, i think there is a issu in the sitepackage.

**Comment by benjaminkott** [comment]
@SchluribumbiVonDerZukunft there was an error in the latest update in the fsc setup - i am sorry for that messed up some keys while porting to symfony 4 should now work again
