### ISSUE TITLE
Does this package works in Typo3 9.5 LTS

### ISSUE THREAD

**Issue by NerxhanMusliu** [benjaminkott/packagebuilder#14]

**Comment by Patta** [comment]
Are you serious?

**Comment by NerxhanMusliu** [comment]
Sure, 

I've installed typo3 9.5 Latest, and when I try to install packagebuilder, an internal 500 Errors appears, (I need to remove package manually, because the typo3 won't let me remove from extension backend module)

**Comment by cedricziel** [comment]
This is a standalone symfony application available to host your own, or use the hosted version at https://sitepackagebuilder.com/.

It will produce an installable package.

You can't just require this package, this won't work.
