### ISSUE TITLE
Make created packages compatible to `bootstrap_package 11.x`

### ISSUE THREAD

**Issue by sgrossberndt** [benjaminkott/packagebuilder#28]
Currently sitepackages created on https://www.sitepackagebuilder.com are compatible to 
`'bootstrap_package' => '10.0.0-10.0.99'`
so they are not compatible to `bootstrap_package 11.x` currently:

https://github.com/benjaminkott/packagebuilder/blob/aed37080255651aa5943f7ccfc5c3f35ac730db0/src/Resources/skeletons/BaseExtension/bootstrap_package/ext_emconf.php.twig#L14

**Comment by benjaminkott** [comment]
@gilbertsoft added support for 10.x, thx for the report
