### ISSUE TITLE
Sitepackage backend layouts not visible in v10.2.2 (bootstrap)

### ISSUE THREAD

**Issue by StaticFluxCreator** [benjaminkott/packagebuilder#34]
Hi,
i used the site package builder already in version 9.5. There a newly created sitepackage (bootstrap) showed the additional Example-Layout. In version 10.2.2 / bootstrap-version 11.0.2 the additional template is not shown. Anyone facing the same issue - did I miss to adjust something?

EDIT: Just to clarify: I installed the sitepackage and assigned it in the root template. No other typo script was used, just the newly generated package.

Thanks and best regards
Florian

**Comment by StaticFluxCreator** [comment]
Ok, I found the error: In the ext.localconf FILE:EXT:' . $_EXTKEY . ' was used and this didn't work completly in v10 anymore. Switching to hardcoded sitepackage name did the job.

 /***************
 * PageTS
 */
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig('<INCLUDE_TYPOSCRIPT: source="FILE:EXT:' . $_EXTKEY . '/Configuration/TsConfig/Page/All.tsconfig">');

**Comment by benjaminkott** [comment]
@flowke1 thx a lot for pointing this out added a bugfix for this - should be deployed in some minutes ❤
