### ISSUE TITLE
ContentElements in Sitepackage not used

### ISSUE THREAD

**Issue by LMSBrubaker** [benjaminkott/packagebuilder#7]
FILE: packagebuilder/src/BK2K/Sitepackage/GeneratorBundle/Resources/skeletons/BaseExtension/bootstrap_package/Configuration/TypoScript/constants.txt.twig

########################
########################
plugin.bootstrap_package_contentelements {
    view {
        layoutRootPath = EXT:{{ package.extensionKey }}/Resources/Private/Layouts/
        partialRootPath = EXT:{{ package.extensionKey }}/Resources/Private/Partials/
        templateRootPath = EXT:{{ package.extensionKey }}/Resources/Private/Templates/
    }
}

Should be:
plugin.bootstrap_package_contentelements {
    view {
        layoutRootPath = EXT:{{ package.extensionKey }}/Resources/Private/Layouts/ContentElements/
        partialRootPath = EXT:{{ package.extensionKey }}/Resources/Private/Partials/ContentElements/
        templateRootPath = EXT:{{ package.extensionKey }}/Resources/Private/Templates/ContentElements/
    }
}

**Comment by benjaminkott** [comment]
@LMSBrubaker thx for pointing this out, fix will be deployed by travis
