### ISSUE TITLE
Display faulty and sitepackage builder does not work

### ISSUE THREAD

**Issue by lucfink** [benjaminkott/packagebuilder#75]
Both the local version and the version at https://www.sitepackagebuilder.com/ show an incorrect display (without CSS and JS) and therefore unfortunately do not work at the moment.
![image](https://user-images.githubusercontent.com/132651458/236404407-fd98d005-089b-404a-baa9-4ddc438a1eb3.png)
![image](https://user-images.githubusercontent.com/132651458/236404618-2c474a64-5e01-40ed-8369-0420cb2248d2.png)
Console:
![image](https://user-images.githubusercontent.com/132651458/236404877-6010a6cb-76b0-4df8-b7f1-0c910ff3632c.png)

**Comment by gilbertsoft** [comment]
Thanks for the report. We were in the progress of updating the app to latest PHP and this task has finished this moring and everything should work fine again.
